(()=>{
  const PATH='/admin';
  const STORE='wagstack-admin-demo-section-v1';
  const demo={
    kpis:[
      ['Today’s bookings','12','+18%','calendar-check'],
      ['Active pets','286','+24 this month','dog'],
      ['Revenue','₱48,620','+12.4%','wallet'],
      ['Club members','94','32.9% of clients','crown']
    ],
    bookings:[
      {time:'9:00 AM',pet:'Mochi',owner:'Andrea Santos',service:'Full Groom',status:'Confirmed'},
      {time:'10:30 AM',pet:'Biscuit',owner:'Marco Reyes',service:'Bath & Brush',status:'Checked in'},
      {time:'12:00 PM',pet:'Luna',owner:'Sofia Lim',service:'Nail + Ear Care',status:'Confirmed'},
      {time:'2:30 PM',pet:'Kobe',owner:'Paolo Cruz',service:'Full Groom',status:'Pending'},
      {time:'5:00 PM',pet:'Pepper',owner:'Mika Tan',service:'Hotel check-in',status:'Confirmed'}
    ],
    clients:[
      {pet:'Mochi',owner:'Andrea Santos',type:'Shih Tzu',last:'Sep 6',points:460,club:'Plus'},
      {pet:'Biscuit',owner:'Marco Reyes',type:'Golden Retriever',last:'Sep 9',points:220,club:'Club'},
      {pet:'Luna',owner:'Sofia Lim',type:'Pomeranian',last:'Aug 28',points:180,club:'—'},
      {pet:'Kobe',owner:'Paolo Cruz',type:'French Bulldog',last:'Sep 1',points:340,club:'Club'},
      {pet:'Pepper',owner:'Mika Tan',type:'Persian Cat',last:'Sep 3',points:515,club:'Plus'}
    ],
    orders:[
      {id:'WS-1048',customer:'Andrea Santos',items:'Cloud Coat Shampoo ×2',total:'₱1,098',status:'Packing'},
      {id:'WS-1047',customer:'Mika Tan',items:'Paw Barrier Balm',total:'₱349',status:'Paid'},
      {id:'WS-1046',customer:'Paolo Cruz',items:'Dental Chews ×2',total:'₱598',status:'Ready'},
      {id:'WS-1045',customer:'Sofia Lim',items:'Treat Puzzle Toy',total:'₱399',status:'Delivered'}
    ],
    members:[
      {name:'Andrea Santos',plan:'Wag Club Plus',pets:'Mochi',since:'Jun 2026',renew:'Sep 24'},
      {name:'Marco Reyes',plan:'Wag Club',pets:'Biscuit',since:'Jul 2026',renew:'Sep 19'},
      {name:'Paolo Cruz',plan:'Wag Club',pets:'Kobe',since:'Aug 2026',renew:'Sep 30'},
      {name:'Mika Tan',plan:'Wag Club Plus',pets:'Pepper',since:'May 2026',renew:'Sep 16'}
    ]
  };
  const icon=(name)=>({
    'calendar-check':'<svg viewBox="0 0 256 256"><path opacity=".2" d="M216 48v40H40V48a8 8 0 0 1 8-8h160a8 8 0 0 1 8 8Z"/><path d="M208 32h-24v-8a8 8 0 0 0-16 0v8H88v-8a8 8 0 0 0-16 0v8H48a16 16 0 0 0-16 16v160a16 16 0 0 0 16 16h160a16 16 0 0 0 16-16V48a16 16 0 0 0-16-16Zm0 176H48V96h160Zm-38-86-48 48-24-24 11-11 13 13 37-37Z"/></svg>',
    dog:'<svg viewBox="0 0 256 256"><path opacity=".2" d="M208 120v64a32 32 0 0 1-32 32H80a32 32 0 0 1-32-32v-64l56-72h48Z"/><path d="m240 125-17-88a16 16 0 0 0-20-13l-52 16h-46L53 24a16 16 0 0 0-20 13l-17 88a16 16 0 0 0 24 17v42a40 40 0 0 0 40 40h96a40 40 0 0 0 40-40v-42a16 16 0 0 0 24-17ZM80 208a24 24 0 0 1-24-24v-61l52-67h40l52 67v61a24 24 0 0 1-24 24h-40v-13l14-13-12-12-10 11-10-11-12 12 14 13v13Z"/></svg>',
    wallet:'<svg viewBox="0 0 256 256"><path opacity=".2" d="M224 72v128a8 8 0 0 1-8 8H40a16 16 0 0 1-16-16V64a16 16 0 0 1 16-16h152a16 16 0 0 1 16 16v8Z"/><path d="M224 64h-16a24 24 0 0 0-24-24H40a24 24 0 0 0-24 24v128a24 24 0 0 0 24 24h176a16 16 0 0 0 16-16V72a8 8 0 0 0-8-8Zm-8 136H40a8 8 0 0 1-8-8V64a8 8 0 0 1 8-8h144a8 8 0 0 1 8 8h-40a32 32 0 0 0 0 64h64Zm0-88h-64a16 16 0 0 1 0-32h64Z"/></svg>',
    crown:'<svg viewBox="0 0 256 256"><path opacity=".2" d="m40 100 48 44 40-72 40 72 48-44-16 100H56Z"/><path d="M248 80a28 28 0 1 0-51 16l-27 33-24-56a28 28 0 1 0-36 0l-24 56-27-33a28 28 0 1 0-27 12l15 87a16 16 0 0 0 16 13h130a16 16 0 0 0 16-13l15-87A28 28 0 0 0 248 80ZM63 192l-14-83 33 40a8 8 0 0 0 14-2l29-67h6l29 67a8 8 0 0 0 14 2l33-40-14 83Z"/></svg>'
  }[name]||'');
  const css=`
  .admin-demo-link{position:relative}.admin-demo-link:after{content:'DEMO';margin-left:auto;font:700 7px Poppins;letter-spacing:.08em;color:#ff7a1a;background:rgba(255,122,26,.11);padding:4px 6px;border-radius:999px}
  .admin{min-height:100%;padding:28px 30px 70px;color:var(--ink,#0b1e3f);font-family:Poppins,sans-serif;background:radial-gradient(circle at 90% 8%,rgba(255,150,77,.14),transparent 28%),radial-gradient(circle at 5% 20%,rgba(55,116,255,.10),transparent 30%)}
  .admin *{box-sizing:border-box}.admin__top{display:flex;align-items:flex-start;justify-content:space-between;gap:18px;margin-bottom:22px}.admin__eyebrow{font-size:9px;font-weight:800;letter-spacing:.14em;text-transform:uppercase;color:#ff7a1a}.admin h1{margin:5px 0 5px;font-size:clamp(28px,4vw,48px);letter-spacing:-.045em;line-height:1}.admin__sub{margin:0;color:#758196;font-size:11px}.admin__actions{display:flex;align-items:center;gap:9px;flex-wrap:wrap;justify-content:flex-end}.admin__pill,.admin__button{border:0;border-radius:999px;padding:10px 14px;font:700 9px Poppins}.admin__pill{background:rgba(255,122,26,.1);color:#d96512;box-shadow:inset 0 0 0 1px rgba(255,122,26,.18)}.admin__button{cursor:pointer;background:#0b1e3f;color:#fff;text-decoration:none}.admin__button--soft{background:rgba(11,30,63,.07);color:inherit;box-shadow:inset 0 0 0 1px rgba(11,30,63,.09)}
  .admin__tabs{display:flex;gap:6px;overflow:auto;padding:4px;margin:0 0 18px;border-radius:16px;background:rgba(255,255,255,.55);box-shadow:inset 0 0 0 1px rgba(11,30,63,.08);backdrop-filter:blur(18px)}.admin__tab{flex:0 0 auto;border:0;border-radius:12px;padding:10px 14px;background:transparent;color:#7a879a;font:700 9px Poppins;cursor:pointer}.admin__tab.is-active{background:#0b1e3f;color:#fff;box-shadow:0 10px 20px -15px rgba(11,30,63,.8)}
  .admin__kpis{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:11px;margin-bottom:11px}.admin__card{position:relative;overflow:hidden;border-radius:22px;background:rgba(255,255,255,.76);box-shadow:inset 0 0 0 1px rgba(11,30,63,.08),0 22px 50px -40px rgba(7,16,31,.42);backdrop-filter:blur(18px)}.admin__kpi{min-height:132px;padding:17px}.admin__kpi-icon{width:35px;height:35px;border-radius:11px;display:grid;place-items:center;background:rgba(255,122,26,.1);color:#ff7a1a}.admin__kpi-icon svg{width:19px;height:19px;fill:currentColor}.admin__kpi-label{margin-top:14px;font-size:8px;font-weight:700;color:#8190a4;text-transform:uppercase;letter-spacing:.08em}.admin__kpi-value{margin-top:3px;font-size:26px;font-weight:800;letter-spacing:-.04em}.admin__kpi-note{margin-top:3px;font-size:8px;color:#758196}
  .admin__grid{display:grid;grid-template-columns:minmax(0,1.55fr) minmax(270px,.75fr);gap:11px}.admin__panel{padding:18px}.admin__head{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:14px}.admin__head h2{margin:0;font-size:14px}.admin__head span{font-size:8px;color:#8692a3}.admin__chart{height:164px;display:flex;align-items:flex-end;gap:8px;padding:16px 6px 0;border-top:1px solid rgba(11,30,63,.06)}.admin__bar{flex:1;min-width:8px;border-radius:8px 8px 3px 3px;background:linear-gradient(180deg,#ff9148,#ff7a1a);opacity:.82;position:relative}.admin__bar:after{content:attr(data-day);position:absolute;top:calc(100% + 8px);left:50%;transform:translateX(-50%);font:600 7px Poppins;color:#92a0b1}.admin__bar:hover{opacity:1}
  .admin__list{display:grid;gap:8px}.admin__activity{display:flex;gap:10px;align-items:center;padding:9px;border-radius:13px;background:rgba(11,30,63,.035)}.admin__dot{width:8px;height:8px;border-radius:50%;background:#ff7a1a;box-shadow:0 0 0 5px rgba(255,122,26,.09)}.admin__activity strong{display:block;font-size:9px}.admin__activity small{display:block;margin-top:2px;color:#8390a1;font-size:7px}
  .admin__table-wrap{overflow:auto;border-radius:18px}.admin__table{width:100%;border-collapse:collapse;min-width:650px}.admin__table th{padding:10px 12px;text-align:left;font-size:7px;letter-spacing:.08em;text-transform:uppercase;color:#8c98a8;border-bottom:1px solid rgba(11,30,63,.07)}.admin__table td{padding:12px;font-size:9px;border-bottom:1px solid rgba(11,30,63,.05)}.admin__table tr:last-child td{border-bottom:0}.admin__table strong{font-size:9px}.admin__status{display:inline-flex;padding:5px 8px;border-radius:999px;background:rgba(11,30,63,.06);font-size:7px;font-weight:700}.admin__status[data-s='Confirmed'],.admin__status[data-s='Paid'],.admin__status[data-s='Ready'],.admin__status[data-s='Checked in']{background:rgba(35,145,91,.10);color:#238456}.admin__status[data-s='Pending'],.admin__status[data-s='Packing']{background:rgba(255,122,26,.11);color:#ce6417}
  .admin__section{display:none}.admin__section.is-active{display:block}.admin__notice{margin-top:11px;padding:12px 15px;border-radius:14px;background:rgba(255,122,26,.08);color:#a75519;font-size:9px;line-height:1.5}.admin__metric-row{display:grid;grid-template-columns:repeat(3,1fr);gap:9px;margin-bottom:11px}.admin__mini{padding:15px}.admin__mini strong{display:block;font-size:18px}.admin__mini span{display:block;margin-top:3px;color:#8290a2;font-size:8px}
  [data-theme='dark'] .admin{color:#eef3fb;background:radial-gradient(circle at 90% 8%,rgba(255,122,26,.12),transparent 28%),#09172b}[data-theme='dark'] .admin__card,[data-theme='dark'] .admin__tabs{background:rgba(19,43,73,.84);box-shadow:inset 0 0 0 1px rgba(255,255,255,.08)}[data-theme='dark'] .admin__button--soft{background:#203f62;color:#eef3fb}[data-theme='dark'] .admin__table th,[data-theme='dark'] .admin__table td{border-color:rgba(255,255,255,.07)}[data-theme='dark'] .admin__activity{background:rgba(255,255,255,.045)}[data-theme='dark'] .admin__sub,[data-theme='dark'] .admin__head span,[data-theme='dark'] .admin__kpi-note,[data-theme='dark'] .admin__kpi-label,[data-theme='dark'] .admin__mini span{color:#b9c5d6}
  @media(max-width:980px){.admin__kpis{grid-template-columns:repeat(2,1fr)}.admin__grid{grid-template-columns:1fr}.admin__metric-row{grid-template-columns:1fr 1fr 1fr}}@media(max-width:620px){.admin{padding:20px 15px 70px}.admin__top{display:grid}.admin__actions{justify-content:flex-start}.admin__kpis{grid-template-columns:1fr 1fr}.admin__kpi{min-height:118px;padding:14px}.admin__kpi-value{font-size:22px}.admin__metric-row{grid-template-columns:1fr}.admin__tabs{border-radius:14px}.admin__tab{padding:9px 11px}.admin__panel{padding:14px}}
  `;
  function installStyle(){if(document.getElementById('wagstack-admin-demo-style'))return;const s=document.createElement('style');s.id='wagstack-admin-demo-style';s.textContent=css;document.head.appendChild(s)}
  function table(headers,rows){return `<div class="admin__table-wrap"><table class="admin__table"><thead><tr>${headers.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div>`}
  function status(s){return `<span class="admin__status" data-s="${s}">${s}</span>`}
  function overview(){return `<section class="admin__section is-active" data-admin-section="overview"><div class="admin__kpis">${demo.kpis.map(k=>`<article class="admin__card admin__kpi"><div class="admin__kpi-icon">${icon(k[3])}</div><div class="admin__kpi-label">${k[0]}</div><div class="admin__kpi-value">${k[1]}</div><div class="admin__kpi-note">${k[2]}</div></article>`).join('')}</div><div class="admin__grid"><article class="admin__card admin__panel"><div class="admin__head"><h2>Revenue this week</h2><span>Demo performance</span></div><div class="admin__chart">${[['M',46],['T',61],['W',53],['T',76],['F',88],['S',100],['S',64]].map(x=>`<div class="admin__bar" data-day="${x[0]}" style="height:${x[1]}%"></div>`).join('')}</div></article><article class="admin__card admin__panel"><div class="admin__head"><h2>Live activity</h2><span>Today</span></div><div class="admin__list"><div class="admin__activity"><i class="admin__dot"></i><div><strong>Biscuit checked in</strong><small>Full Groom · 8 min ago</small></div></div><div class="admin__activity"><i class="admin__dot"></i><div><strong>New Wag Club member</strong><small>Andrea upgraded to Plus · 21 min ago</small></div></div><div class="admin__activity"><i class="admin__dot"></i><div><strong>Order WS-1048 paid</strong><small>₱1,098 · 34 min ago</small></div></div><div class="admin__activity"><i class="admin__dot"></i><div><strong>Hotel request received</strong><small>Pepper · Sep 14–16</small></div></div></div></article></div><article class="admin__card admin__panel" style="margin-top:11px"><div class="admin__head"><h2>Today’s schedule</h2><span>5 upcoming</span></div>${bookingTable()}</article></section>`}
  function bookingTable(){return table(['Time','Pet / Parent','Service','Status'],demo.bookings.map(x=>`<tr><td><strong>${x.time}</strong></td><td><strong>${x.pet}</strong><br><span>${x.owner}</span></td><td>${x.service}</td><td>${status(x.status)}</td></tr>`))}
  function bookings(){return `<section class="admin__section" data-admin-section="bookings"><div class="admin__metric-row"><article class="admin__card admin__mini"><strong>12</strong><span>Bookings today</span></article><article class="admin__card admin__mini"><strong>3</strong><span>Waiting confirmation</span></article><article class="admin__card admin__mini"><strong>86%</strong><span>Weekly capacity</span></article></div><article class="admin__card admin__panel"><div class="admin__head"><h2>Booking manager</h2><span>Grooming + hotel</span></div>${bookingTable()}</article></section>`}
  function clients(){return `<section class="admin__section" data-admin-section="clients"><div class="admin__metric-row"><article class="admin__card admin__mini"><strong>286</strong><span>Active pet profiles</span></article><article class="admin__card admin__mini"><strong>214</strong><span>Fur parents</span></article><article class="admin__card admin__mini"><strong>74%</strong><span>Repeat booking rate</span></article></div><article class="admin__card admin__panel"><div class="admin__head"><h2>Pet & client directory</h2><span>Demo profiles</span></div>${table(['Pet','Fur parent','Breed','Last visit','Paw Points','Club'],demo.clients.map(x=>`<tr><td><strong>${x.pet}</strong></td><td>${x.owner}</td><td>${x.type}</td><td>${x.last}</td><td>${x.points}</td><td>${x.club}</td></tr>`))}</article></section>`}
  function orders(){return `<section class="admin__section" data-admin-section="orders"><div class="admin__metric-row"><article class="admin__card admin__mini"><strong>₱12,840</strong><span>Shop revenue this month</span></article><article class="admin__card admin__mini"><strong>18</strong><span>Open orders</span></article><article class="admin__card admin__mini"><strong>₱611</strong><span>Average order</span></article></div><article class="admin__card admin__panel"><div class="admin__head"><h2>Orders</h2><span>Latest transactions</span></div>${table(['Order','Customer','Items','Total','Status'],demo.orders.map(x=>`<tr><td><strong>${x.id}</strong></td><td>${x.customer}</td><td>${x.items}</td><td><strong>${x.total}</strong></td><td>${status(x.status)}</td></tr>`))}</article></section>`}
  function memberships(){return `<section class="admin__section" data-admin-section="memberships"><div class="admin__metric-row"><article class="admin__card admin__mini"><strong>94</strong><span>Active members</span></article><article class="admin__card admin__mini"><strong>₱38,520</strong><span>Recurring monthly value</span></article><article class="admin__card admin__mini"><strong>32.9%</strong><span>Client membership rate</span></article></div><article class="admin__card admin__panel"><div class="admin__head"><h2>Memberships</h2><span>Wag Club</span></div>${table(['Member','Plan','Pet','Member since','Next renewal'],demo.members.map(x=>`<tr><td><strong>${x.name}</strong></td><td>${x.plan}</td><td>${x.pets}</td><td>${x.since}</td><td>${x.renew}</td></tr>`))}</article></section>`}
  function shell(){return `<section class="admin"><header class="admin__top"><div><div class="admin__eyebrow">WagStack for Business</div><h1>Admin Dashboard</h1><p class="admin__sub">One place to run grooming, hotel stays, pet records, rewards, memberships and shop orders.</p></div><div class="admin__actions"><span class="admin__pill">Guest Admin · Demo Data</span><a class="admin__button admin__button--soft" href="/" data-admin-customer>View customer app</a><button class="admin__button" type="button" data-admin-demo-action>New booking</button></div></header><nav class="admin__tabs" aria-label="Admin dashboard sections">${[['overview','Overview'],['bookings','Bookings'],['clients','Pets & Clients'],['orders','Orders'],['memberships','Memberships']].map(x=>`<button class="admin__tab" data-admin-tab="${x[0]}">${x[1]}</button>`).join('')}</nav>${overview()}${bookings()}${clients()}${orders()}${memberships()}<div class="admin__notice">Preview mode uses curated demo data only. Real customer records and production controls are intentionally not exposed to guest visitors.</div></section>`}
  function setSection(name){const valid=['overview','bookings','clients','orders','memberships'].includes(name)?name:'overview';try{sessionStorage.setItem(STORE,valid)}catch{}document.querySelectorAll('[data-admin-tab]').forEach(b=>b.classList.toggle('is-active',b.dataset.adminTab===valid));document.querySelectorAll('[data-admin-section]').forEach(s=>s.classList.toggle('is-active',s.dataset.adminSection===valid))}
  function render(){if(location.pathname!==PATH)return;installStyle();const main=document.querySelector('#main-content');if(!main)return;if(main.dataset.adminDemo==='1')return;main.dataset.adminDemo='1';main.className='shell__panel';main.removeAttribute('data-fixed');main.innerHTML=shell();document.title='WagStack Admin — Guest Demo';let active='overview';try{active=sessionStorage.getItem(STORE)||'overview'}catch{}setSection(active)}
  function addRailLink(){const nav=document.querySelector('.rail__nav ul');if(!nav||nav.querySelector('[data-admin-demo-link]'))return;const li=document.createElement('li');li.innerHTML='<a class="rail__link admin-demo-link" data-admin-demo-link href="/admin"><span aria-hidden="true" class="ricon ricon--phosphor"><svg class="ph-duo ph-duo--nav" viewBox="0 0 256 256" fill="currentColor"><path opacity=".2" d="M40 56h176v144H40z"/><path d="M216 40H40a16 16 0 0 0-16 16v144a16 16 0 0 0 16 16h176a16 16 0 0 0 16-16V56a16 16 0 0 0-16-16ZM96 200H40V136h56Zm0-80H40V56h56Zm120 80H112V136h104Zm0-80H112V56h104Z"/></svg></span>Admin</a>';nav.appendChild(li)}
  document.addEventListener('click',e=>{const tab=e.target.closest('[data-admin-tab]');if(tab){e.preventDefault();setSection(tab.dataset.adminTab);return}const demo=e.target.closest('[data-admin-demo-link]');if(demo){e.preventDefault();history.pushState({path:PATH},'',PATH);const main=document.querySelector('#main-content');if(main)delete main.dataset.adminDemo;render();return}const customer=e.target.closest('[data-admin-customer]');if(customer){e.preventDefault();history.pushState({path:'/'},'','/');location.reload();return}if(e.target.closest('[data-admin-demo-action]')){e.preventDefault();const n=document.createElement('div');n.className='wagstack-ai-note';n.textContent='Demo mode: write actions are disabled for prospects.';document.body.appendChild(n);setTimeout(()=>n.remove(),2600)}},true);
  addEventListener('popstate',()=>{if(location.pathname===PATH){const main=document.querySelector('#main-content');if(main)delete main.dataset.adminDemo;render()}});
  installStyle();addRailLink();render();new MutationObserver(()=>{addRailLink();render()}).observe(document.body,{childList:true,subtree:true});
})();