import './v26-core.js';
import './v27-patch.js';
import './supabase-bridge.js';
import './rail-auth.js';
import './shop-production.js';
import './updates-production.js';
import './supabase-normalized.js';
import './supabase-reward-log.js';
import './v34-guest-avatar.js';
import './v36-admin-separate-addpet.js';
import './admin-production.js';
import './admin-readability.js';
import './admin-theme.js';
import './admin-content-management.js';
import './v37-admin-entry-cleanup.js';
setTimeout(() => import('./v29-critical.js'), 0);
