import './v26-core.js';
import './v27-patch.js';
import './supabase-bridge.js';
import './supabase-normalized.js';
import './supabase-reward-log.js';
import './v34-guest-avatar.js';
import './admin-demo.js';
import './v36-admin-separate-addpet.js';
import './v37-admin-entry-cleanup.js';
setTimeout(()=>import('./v29-critical.js'),0);
