import assert from 'node:assert/strict';
import { snapshot, decide } from '../supabase/functions/carousel-weather/logic.mjs';
const now = Date.parse('2026-09-14T01:10:00Z');
const prev = { temperature: 28, wind: 8, rain: 0, rainLevel: 0, hot: false, windy: false, forecastAt: '2026-09-14T00:00:00Z', checkedAt: '2026-09-14T00:40:00Z' };
const current = { ...prev, temperature: 28.8, forecastAt: '2026-09-14T01:00:00Z', checkedAt: new Date(now).toISOString() };
assert.equal(decide(null, current).publish, true);
assert.equal(decide(prev, current, [prev], null, now).publish, false, 'small changes remain stable');
assert.equal(decide(prev, { ...current, condition: 'Cloudy skies' }, [prev], null, now).publish, false, 'cloud cover alone is not sudden');
assert.equal(decide(prev, { ...current, rainLevel: 1 }, [], null, now).publish, true, 'rain onset publishes');
assert.equal(decide(prev, { ...current, rainLevel: 3 }, [], null, now).publish, true, 'thunder publishes immediately');
assert.equal(decide(prev, { ...current, wind: 36 }, [], null, now).publish, true);
assert.equal(decide(prev, { ...current, temperature: 32 }, [], null, now).publish, true);
assert.equal(decide(prev, { ...current, temperature: 24 }, [prev], null, now).publish, true, 'sharp hourly temperature shift');
assert.equal(decide(prev, { ...current, temperature: 24 }, [{ ...prev, checkedAt: '2026-09-13T01:00:00Z' }], null, now).publish, false, 'old observations cannot imply sudden shift');
const rain = { ...prev, rainLevel: 2 };
const pending = decide(rain, current, [], null, now);
assert.equal(pending.publish, false);
assert.equal(decide(rain, current, [], pending.candidate, now + 10 * 60e3).publish, true, 'recovery must persist');
assert.equal(decide({ ...prev, hot: true }, { ...current, temperature: 31.8 }, [], null, now).publish, false, 'heat threshold hysteresis');
assert.throws(() => snapshot({ properties: { meta: { updated_at: '2026-01-01' }, timeseries: [] } }, now));
console.log('Weather checks passed: stable conditions, rain/thunder/wind/heat, sharp changes, recovery hysteresis and stale data.');
